### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by digdug82** [juvs/s3-bucket-browser#3]
Error: Could not load objects from S3
I'm using wamp, I didn't test it on a real server.

**Comment by abhishekq61** [comment]
Same,issue

**Comment by TonySqrd** [comment]
Same issue here.

**Comment by webdevbyjoss** [comment]
guys, can you share some test s3 credentials, where this issue can be reproducible?
just wondering if there are permissions or any other restrictive settings that may result into this issue
